#!/usr/bin/python

import re

id=1
#for state in range(56):
#s = "{0:0}".format(state+1)
#if len(s) == 1:
#	s = "0" + s
f = open('eiaC1.html', 'r')
res = str(id)
l = f.readline()
nbCols = 0;
while l:
	if l.startswith('<td  colspan="1"  align="left"'):
		m = re.search('(?<=Helvetica">)[^<]+', l)
		res = res + "\t" + m.group(0).replace("&nbsp;", " ")

	 	l = f.readline()
		col = 0
		while not l.startswith('<td  colspan="1"  align="left"'):
			if l.startswith('<td'):
				#print ">>" + l
				col = col + 1
				if id == 1:
					nbCols = col
				else:
					if col>nbCols:
						break
				m = re.search('(?<=Helvetica">)[^<]+', l)
				res = res + "\t" + m.group(0)
				
			l = f.readline()
			
		print res
		id = id + 1
		res = str(id)
		
	else:
		l = f.readline()
